from app.agents.research_agent import ResearchAgent
from app.agents.article_agent import ArticleAgent
from app.strategy.brand_strategy import BrandStrategy

from app.agents.entity_agent import EntityAgent
from app.agents.seo_agent import SEOAgent
from app.agents.seo_scorer import SEOScorer
from app.agents.internal_linking_agent import InternalLinkingAgent
from app.agents.eeat_agent import EEATAgent
from app.agents.schema_generator import SchemaGenerator, generate_full_schema_set
from app.agents.verdicts_generator import VerdictGenerator
from app.agents.data_freshness_agent import DataFreshnessAgent
from app.agents.localization_agent import DynamicDatingAgent, LocalizationAgent
import os
import html
import json
try:
    import markdown
except ImportError:
    markdown = None
from app.services.memory_service import MemoryService
from app.agents.site_brain_agent import SiteBrainAgent
from app.agents.citation_optimizer_agent import CitationOptimizerAgent
from app.agents.query_simulator_agent import QuerySimulatorAgent
from app.agents.topic_discovery_agent import TopicDiscoveryAgent
from app.config.brand_configs import get_brand_config







class ArticleWorkflow:
    def __init__(self):
        self.query_agent = QuerySimulatorAgent()
        self.citation_agent = CitationOptimizerAgent()
        self.site_brain = SiteBrainAgent()
        self.memory = MemoryService()
        self.internal_linking_agent = InternalLinkingAgent()
        self.research_agent = ResearchAgent()
        self.brand_agent = BrandStrategy()
        self.entity_agent = EntityAgent()
        self.article_agent = ArticleAgent()
        self.seo_agent = SEOAgent()
        self.seo_scorer = SEOScorer()
        # NEW: Add EEAT + Schema + Verdicts agents
        self.eeat_agent = EEATAgent()
        self.schema_generator = SchemaGenerator()
        self.verdicts_generator = VerdictGenerator()
        # NEW: Data Freshness agent for 2026-current content
        self.freshness_agent = DataFreshnessAgent()
        self.dating_agent = DynamicDatingAgent()
        self.localization_agent = LocalizationAgent()
        self.topic_discovery_agent = TopicDiscoveryAgent()

    def _build_html(
        self,
        article_content: str,
        meta_title: str,
        meta_description: str,
        canonical_url: str | None = None,
        schemas: list | None = None,
    ) -> str:
        if markdown is None:
            raise RuntimeError("The markdown package is required. Install it with: pip install markdown")

        html_body = markdown.markdown(article_content, extensions=["extra", "tables"])
        safe_title = html.escape(meta_title)
        safe_desc = html.escape(meta_description[:160].strip())
        page_url = canonical_url or ""
        schema_script = ""

        if schemas:
            schema_json = json.dumps(schemas, ensure_ascii=False, indent=2)
            schema_script = f"""
<script type=\"application/ld+json\">
{schema_json}
</script>
"""

        return f"""<!doctype html>
<html lang=\"ko\">
<head>
<meta charset=\"UTF-8\">
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
<title>{safe_title}</title>
<meta name=\"description\" content=\"{safe_desc}\">
<meta property=\"og:type\" content=\"article\">
<meta property=\"og:title\" content=\"{safe_title}\">
<meta property=\"og:description\" content=\"{safe_desc}\">
<meta property=\"og:locale\" content=\"ko_KR\">
{f'<meta property="og:url" content="{page_url}">' if page_url else ''}
{f'<link rel="canonical" href="{page_url}">' if page_url else ''}
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.7; color: #202124; margin: 0; padding: 0; background: #fff; }}
.page-shell {{ max-width: 1024px; margin: auto; padding: 24px; }}
.page-header {{ margin-bottom: 24px; }}
.page-header h1 {{ font-size: 2.4rem; margin: 0 0 12px; }}
.page-header p {{ color: #4d4d4d; margin: 0; }}
.article-body {{ display: grid; gap: 24px; }}
.article-body article {{ counter-reset: section; }}
.article-body h2 {{ margin-top: 2rem; }}
.article-body h3 {{ margin-top: 1.5rem; }}
.article-body img {{ max-width: 100%; height: auto; }}
.article-body table {{ width: 100%; border-collapse: collapse; }}
.article-body table, .article-body th, .article-body td {{ border: 1px solid #ddd; }}
.article-body th, .article-body td {{ padding: 12px; text-align: left; }}
.page-footer {{ margin-top: 48px; padding-top: 24px; border-top: 1px solid #e2e2e2; color: #6a737d; font-size: 0.95rem; }}
</style>
</head>
<body>
<div class=\"page-shell\">
<header class=\"page-header\">
<h1>{safe_title}</h1>
<p>{safe_desc}</p>
</header>
<main class=\"article-body\">
<article>
{html_body}
</article>
</main>
<footer class=\"page-footer\">
<p>Generated by the AI SEO automation engine for GEO/LLM-ready content.</p>
</footer>
</div>
{schema_script}
</body>
</html>
"""

    def _detect_brand_info(self, text: str | None):
        text_lower = (text or "").lower()
        if any(keyword in text_lower for keyword in ["lg gram", "lg", "notebook", "laptop", "ultrabook"]):
            return "lg_notebook", "LG Gram", "laptop"
        if "dongwon" in text_lower or "salmon" in text_lower:
            return "dongwon_salmon", "Dongwon", "salmon"
        if any(keyword in text_lower for keyword in ["doshinji", "ceramic", "ceramics"]):
            return "doshinji_ceramics", "Doshinji", "ceramics"
        return None, None, None

    def get_existing_topics(self):
        folder = "outputs"
        if not os.path.exists(folder):
            return []

        files = os.listdir(folder)
        topics = [f.replace(".md", "").replace("_", " ") for f in files]
        return topics

    def run(self, topic: str | None = None, niche: str | None = None):
        if not topic and not niche:
            raise ValueError("Topic or niche is required")

        if not topic and niche:
            print(f"🧠 Discovering best topic for niche: {niche}")
            discovery = self.topic_discovery_agent.discover_topic(niche)
            topic = discovery.get("selected_topic") or niche
            print(f"✅ Discovered topic: {topic}")

        print("Researching...")
        topic_lower = topic.lower() if topic else ""
        brand_key, brand, product_type = self._detect_brand_info(topic or niche)

        if not brand_key and niche:
            brand_key, brand, product_type = self._detect_brand_info(niche)

        official_link = None
        if brand_key:
            brand_config = get_brand_config(brand_key)
            if brand_config:
                official_link = brand_config.get("product_pages", [brand_config.get("official_website")])[0]

        if brand_key == "lg_notebook":
            official_link = "https://www.lge.co.kr/laptop"

        if brand_key is None:
            product_type = "laptop"

        research_data = self.research_agent.research(
            topic,
            brand=brand,
            product_type=product_type,
            brand_key=brand_key
        )

        print("Brand strategy...")
        brand_voice = self.brand_agent.get_strategy(topic)

        print("Extracting SEO entities...")
        entities = self.entity_agent.extract_entities(research_data)

        # Extract brand name early for use in multiple agents
        brand_name = topic.split()[0] if topic else "Product"

        # Infer category for current specs enforcement
        topic_lower = topic.lower() if topic else ""
        if any(keyword in topic_lower for keyword in ["laptop", "notebook", "ultrabook", "lg gram"]):
            category = "laptop"
        elif "salmon" in topic_lower:
            category = "salmon"
        elif any(keyword in topic_lower for keyword in ["ceramic", "ceramics", "doshinji"]):
            category = "ceramics"
        else:
            category = "laptop"

        current_specs = self.freshness_agent.get_current_specs(brand_name, category)
        specs_data = (
            "CURRENT 2026 SPECS (override any older data):\n"
            f"{current_specs}\n\n"
            "RECENCY RULE: Use Intel Core Ultra (2025/2026 generation) or at minimum 13th/14th Gen."
            " Avoid 11th/12th Gen references.\n"
            "COMPARISON NOTE: MacBook Air M3 weight is ~1.24 kg, while LG Gram 13 is ~0.99 kg."
        )

        print("Generating article...")
        article = self.article_agent.generate_article(
            topic=topic,
            research_data=research_data,
            brand_voice=brand_voice,
            entities=entities,
            specs_data=specs_data,
            official_link=official_link
        )

        print("Generating SEO search queries...")
        seo_queries = self.seo_agent.generate_search_queries(topic)

        print("Generating FAQ...")
        faq = self.seo_agent.generate_faq(topic)

        article = self.freshness_agent.normalize_processor_mentions(article)

        print("SEO optimizing...")
        optimized_article = self.seo_agent.optimize_article(article, entities)
        optimized_article = self.freshness_agent.normalize_processor_mentions(optimized_article)

        print("Validating data freshness (2026-current standards)...")
        freshness_report = self.freshness_agent.validate_article_freshness(optimized_article)
        named_entities = self.freshness_agent.extract_named_entities(optimized_article, brand_name)
        
        # Add freshness metadata for memory
        if not freshness_report.get("is_current", True):
            print(f"⚠️  Data freshness issues detected: {freshness_report.get('issues_found', [])}")
        
        expert_verdict = self.freshness_agent.generate_expert_verdict_block(
            product=brand_name,
            key_strength="Premium quality and performance",
            target_audience="Professionals and students",
            competitive_advantage="Best value-to-performance ratio"
        )

        print("Adding EEAT signals (expert quotes, authority)...")
        expert_quotes = self.eeat_agent.generate_expert_quotes(topic, brand_name, num_quotes=2)
        authority_signals = self.eeat_agent.generate_authority_signals(topic, brand_name)

        print("Generating AI verdicts (quote-ready statements)...")
        verdict_section = self.verdicts_generator.generate_complete_verdict_section(
            product=brand_name,
            key_specs={
                "Quality": "Premium grade",
                "Availability": "Widely available",
                "Rating": "High customer satisfaction"
            },
            use_cases=["General use", "Professional use", "Consumer preferences"],
            competitors=["Competitor A", "Competitor B", "Competitor C"]
        )

        print("Generating JSON-LD schemas...")
        faqs = [{"question": q, "answer": a} for q, a in zip(
            ["Q1", "Q2"],
            ["A1", "A2"]
        )]
        breadcrumbs = [
            {"name": "Home", "url": "/"},
            {"name": topic.title(), "url": f"/{topic.lower().replace(' ', '-')}"}
        ]
        schemas = generate_full_schema_set(
            article_title=topic,
            article_description=optimized_article[:200],
            product_name=brand_name,
            brand_name=brand_name,
            faqs=faqs,
            breadcrumbs=breadcrumbs
        )

        print("Scoring article SEO quality...")
        seo_score = self.seo_scorer.score_article(optimized_article, topic)
        
        print(" Generating internal links...")
        existing_topics = self.get_existing_topics()
        related_links = self.internal_linking_agent.generate_links(topic, existing_topics)

        # Добавляем внутренние ссылки в статью
        article_with_links = article + f"\n\n## Related Articles\n{related_links}"
        
        # 🌍 Apply dynamic dating and localization for 10/10 quality
        print("📅 Updating article dates to current year...")
        article_with_links = self.dating_agent.update_article_dates(article_with_links)
        
        print("🌏 Adding regional localization for Korea...")
        article_with_links = self.localization_agent.add_regional_context(
            article_with_links, 
            brand_name, 
            region="korea"
        )
        
        # Generate Korea-specific verdict
        localized_verdict = self.localization_agent.generate_localized_verdict(brand_name, region="korea")
        print(f"✨ Regional Verdict: {localized_verdict}")
        
        print("Rendering HTML output...")
        canonical_url = os.getenv("GITHUB_PAGES_URL")
        html_article = self._build_html(
            article_with_links,
            meta_title=topic,
            meta_description=optimized_article[:160],
            canonical_url=canonical_url,
            schemas=schemas,
        )
        
        # Сохраняем данные в память
        memory_entry = {
            "seo_score": seo_score,
            "entities": entities,
            "related_links": related_links,
            "seo_queries": seo_queries,
            "faq": faq,
            "expert_quotes": expert_quotes,
            "authority_signals": authority_signals,
            "verdicts": verdict_section,
            "schemas": schemas,
            "localized_verdict": localized_verdict
        }
        self.memory.save_article_record(topic, memory_entry)

        print(" Planning next articles...")
        next_plan = self.site_brain.plan_next_articles(topic, memory_entry)

        print("\n=== NEXT CONTENT STRATEGY ===")
        print(next_plan)

        return {
            "topic": topic,
            "raw_article": article,
            "seo_queries": seo_queries,
            "faq": faq,
            "article": article_with_links,
            "html_article": html_article,
            "optimized_article": optimized_article,
            "seo_score": seo_score,
            "expert_quotes": expert_quotes,
            "authority_signals": authority_signals,
            "verdicts": verdict_section,
            "schemas": schemas
        }
